export const OBJECT_LOCALIZATION = "OBJECT_LOCALIZATION";
export const LABEL_DETECTION = "LABEL_DETECTION";
export const IMAGE_PROPERTIES = "IMAGE_PROPERTIES";
export const SAFE_SEARCH_DETECTION = "SAFE_SEARCH_DETECTION";
export const FACE_DETECTION = "FACE_DETECTION";
